// packages/plugin-a11y/src/vue/components/a11y-layer.vue
<script setup lang="ts">
import { ref, watchEffect, toRefs } from 'vue';
import type { StructElement } from '@embedpdf/plugin-a11y';
import { useA11yCapability } from '../hooks';

const props = defineProps<{ pageIndex: number; scale: number }>();
const { pageIndex, scale } = toRefs(props);

const { provides } = useA11yCapability();
const elements = ref<StructElement[]>([]);

watchEffect(() => {
  if (!provides.value) {
    elements.value = [];
    return;
  }
  provides.value
    .getStructElements(pageIndex.value)
    .then((els) => (elements.value = els))
    .catch(() => (elements.value = []));
});
</script>

<template>
  <div v-if="elements.length" style="position: absolute; left: 0; top: 0">
    <component
      v-for="(el, i) in elements"
      :is="el.htmlTag"
      :key="i"
      :style="{
        position: 'absolute',
        left: el.rect.origin.x * scale + 'px',
        top: el.rect.origin.y * scale + 'px',
        width: el.rect.size.width * scale + 'px',
        height: el.rect.size.height * scale + 'px'
      }"
      :role="el.attributes?.role"
      :aria-label="el.text"
    >
      {{ el.text }}
    </component>
  </div>
</template>

// packages/plugin-a11y/src/shared/components/a11y-layer.tsx
import { StructElement } from '@embedpdf/plugin-a11y';
import { useEffect, useState } from '@framework';

import { useA11yCapability } from '../hooks';

type Props = {
  pageIndex: number;
  scale: number;
};

export function A11yLayer({ pageIndex, scale }: Props) {
  const { provides } = useA11yCapability();
  const [elements, setElements] = useState<StructElement[]>([]);

  useEffect(() => {
    if (!provides) return;
    provides
      .getStructElements(pageIndex)
      .then(setElements)
      .catch(() => setElements([]));
  }, [provides, pageIndex]);

  if (!elements.length) return null;

  return (
    <div style={{ position: 'absolute', left: 0, top: 0 }}>
      {elements.map((el, i) => {
        const Tag = el.htmlTag as any;
        const style = {
          position: 'absolute' as const,
          left: el.rect.origin.x * scale,
          top: el.rect.origin.y * scale,
          width: el.rect.size.width * scale,
          height: el.rect.size.height * scale,
        };
        return (
          <Tag key={i} style={style} role={el.attributes?.role} aria-label={el.text}>
            {el.text}
          </Tag>
        );
      })}
    </div>
  );
}
