// packages/plugin-a11y/src/vue/components/struct-element-component.vue
<script setup lang="ts">
import { toRefs } from 'vue';
import type { StructElement } from '@embedpdf/plugin-a11y';

  const props = defineProps<{ 
    element: StructElement;  
    scale: number;  
    parentLang?: string; 
  }>();
  const { element, scale, parentLang } = toRefs(props);
  const Tag = (element.value.htmlTag || 'span') as any;
  
  const attrs: Record<string, string> = { ...(element.value.attributes || {}) };
  if (element.value.language && element.value.language !== parentLang.value) {
    attrs.lang = element.value.language;
  }

  const style = {
    left: element.value.rect.origin.x * scale.value || undefined,
    top: element.value.rect.origin.y * scale.value || undefined,
    width: element.value.rect.size.width * scale.value || undefined,
    height: element.value.rect.size.height * scale.value || undefined,
  };

</script>

<template>
  <component
    :is="Tag"
    :style="style"
    :attrs="attrs"  >
    {{ element.text }}
  </component>
</template>

// packages/plugin-a11y/src/shared/components/struct-element.tsx
import type { StructElement as StructElementModel } from '@embedpdf/plugin-a11y';

interface Props {
  element: StructElementModel;
  scale: number;
  mcidMap: Map<number, string>;
}

export function StructElement({ element, scale, mcidMap }: Props) {
  const Tag = (element.htmlTag || 'span') as any;

  const existingIds = element.mcids
    .map((mcid) => mcidMap.get(mcid))
    .filter((id): id is string => Boolean(id));

  let id: string | undefined;
  if (existingIds.length === 0 && element.mcids.length) {
    id = `mcid-${element.mcids[0]}`;
    element.mcids.forEach((mcid) => mcidMap.set(mcid, id!));
  }

  const ariaProps = existingIds.length ? { 'aria-labelledby': existingIds.join(' ') } : {};

  const style = {
    position: 'absolute' as const,
    left: element.rect.origin.x * scale,
    top: element.rect.origin.y * scale,
    width: element.rect.size.width * scale,
    height: element.rect.size.height * scale,
  };

  return (
    <Tag {...element.attributes} {...(id && { id })} {...ariaProps} style={style}>
      {existingIds.length ? null : element.text}
      {element.children.map((child, i) => (
        <StructElement key={i} element={child} scale={scale} mcidMap={mcidMap} />
      ))}
    </Tag>
  );
}
