// packages/plugin-ui/src/svelte/root.svelte
<script lang="ts">
  import { UI_ATTRIBUTES } from '@embedpdf/plugin-ui';
  import { createStyleSheetOwner, getStyleSheetRegistry } from '@embedpdf/utils';
  import { useUIPlugin, useUICapability } from './hooks/use-ui.svelte';
  import { setUIContainerContext } from './hooks/use-ui-container.svelte';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = HTMLAttributes<HTMLDivElement> & {
    children?: Snippet;
  };

  let { children, class: className, ...restProps }: Props = $props();

  const { plugin } = useUIPlugin();
  const { provides } = useUICapability();

  let disabledCategories = $state<string[]>([]);
  let hiddenItems = $state<string[]>([]);
  let rootElement: HTMLDivElement | null = $state(null);
  const styleOwner = createStyleSheetOwner('@embedpdf/plugin-ui/svelte');

  // Provide container context for child components
  setUIContainerContext({
    getContainer: () => rootElement,
  });

  function getStyleRoot(element: HTMLElement): Document | ShadowRoot {
    const root = element.getRootNode();
    if (root.nodeType === 11 && 'host' in root) {
      return root as ShadowRoot;
    }
    return element.ownerDocument;
  }

  $effect(() => {
    if (!rootElement || !plugin) {
      return;
    }

    const currentPlugin = plugin;
    const lease = getStyleSheetRegistry(getStyleRoot(rootElement)).register({
      owner: styleOwner,
      slot: 'generated-ui',
      order: 100,
      css: currentPlugin.getStylesheet(),
    });
    const unsubscribe = currentPlugin.onStylesheetInvalidated(() => {
      lease.update(currentPlugin.getStylesheet());
    });

    return () => {
      unsubscribe();
      lease.dispose();
    };
  });

  $effect(() => {
    if (!provides) return;

    disabledCategories = provides.getDisabledCategories();
    hiddenItems = provides.getHiddenItems();

    return provides.onCategoryChanged((event) => {
      disabledCategories = event.disabledCategories;
      hiddenItems = event.hiddenItems;
    });
  });

  const disabledCategoriesAttr = $derived(
    disabledCategories.length > 0 ? disabledCategories.join(' ') : undefined,
  );

  const hiddenItemsAttr = $derived(hiddenItems.length > 0 ? hiddenItems.join(' ') : undefined);
</script>

<div
  bind:this={rootElement}
  {...restProps}
  {...{ [UI_ATTRIBUTES.ROOT]: '' }}
  {...disabledCategoriesAttr ? { [UI_ATTRIBUTES.DISABLED_CATEGORIES]: disabledCategoriesAttr } : {}}
  {...hiddenItemsAttr ? { [UI_ATTRIBUTES.HIDDEN_ITEMS]: hiddenItemsAttr } : {}}
  class={className}
  style:container-type="inline-size"
>
  {#if children}
    {@render children()}
  {/if}
</div>

// packages/plugin-ui/src/shared/root.tsx
import { UI_ATTRIBUTES } from '@embedpdf/plugin-ui';
import {
  createStyleSheetOwner,
  getStyleSheetRegistry,
  type StyleSheetLease,
} from '@embedpdf/utils';
import {
  useState,
  useEffect,
  useRef,
  useMemo,
  useCallback,
  ReactNode,
  HTMLAttributes,
} from '@framework';

import { useUICapability, useUIPlugin } from './hooks/use-ui';
import { UIContainerContext, UIContainerContextValue } from './hooks/use-ui-container';

function getStyleRoot(element: HTMLElement): Document | ShadowRoot {
  const root = element.getRootNode();
  if (root.nodeType === 11 && 'host' in root) {
    return root as ShadowRoot;
  }
  return element.ownerDocument;
}

interface UIRootProps extends HTMLAttributes<HTMLDivElement> {
  children: ReactNode;
}

/**
 * Internal component that handles:
 * 1. Injecting the generated stylesheet (into shadow root or document.head)
 * 2. Managing the data-disabled-categories attribute
 * 3. Updating styles on locale changes
 */
export function UIRoot({ children, style, ...restProps }: UIRootProps) {
  const { plugin } = useUIPlugin();
  const { provides } = useUICapability();
  const [disabledCategories, setDisabledCategories] = useState<string[]>([]);
  const [hiddenItems, setHiddenItems] = useState<string[]>([]);
  const styleLeaseRef = useRef<StyleSheetLease | null>(null);
  const styleOwnerRef = useRef<string | null>(null);
  let styleOwner = styleOwnerRef.current;
  if (!styleOwner) {
    styleOwner = createStyleSheetOwner('@embedpdf/plugin-ui/react');
    styleOwnerRef.current = styleOwner;
  }
  const containerRef = useRef<HTMLDivElement>(null);

  // Create container context value (memoized to prevent unnecessary re-renders)
  const containerContextValue = useMemo<UIContainerContextValue>(
    () => ({
      containerRef,
      getContainer: () => containerRef.current,
    }),
    [],
  );

  const rootRefCallback = useCallback(
    (element: HTMLDivElement | null) => {
      (containerRef as any).current = element;
      styleLeaseRef.current?.dispose();
      styleLeaseRef.current = null;

      if (!element || !plugin) {
        return;
      }

      styleLeaseRef.current = getStyleSheetRegistry(getStyleRoot(element)).register({
        owner: styleOwner,
        slot: 'generated-ui',
        order: 100,
        css: plugin.getStylesheet(),
      });
    },
    [plugin, styleOwner],
  );

  // Subscribe to stylesheet invalidation (locale changes, schema merges)
  useEffect(() => {
    if (!plugin) return;

    return plugin.onStylesheetInvalidated(() => {
      styleLeaseRef.current?.update(plugin.getStylesheet());
    });
  }, [plugin]);

  // Subscribe to category and hidden items changes
  useEffect(() => {
    if (!provides) return;

    setDisabledCategories(provides.getDisabledCategories());
    setHiddenItems(provides.getHiddenItems());

    return provides.onCategoryChanged(({ disabledCategories, hiddenItems }) => {
      setDisabledCategories(disabledCategories);
      setHiddenItems(hiddenItems);
    });
  }, [provides]);

  // Build the disabled categories attribute value
  const disabledCategoriesAttr = useMemo(
    () => (disabledCategories.length > 0 ? disabledCategories.join(' ') : undefined),
    [disabledCategories],
  );

  // Build the hidden items attribute value
  const hiddenItemsAttr = useMemo(
    () => (hiddenItems.length > 0 ? hiddenItems.join(' ') : undefined),
    [hiddenItems],
  );

  const combinedStyle = useMemo(() => {
    const base = { containerType: 'inline-size' as const };
    if (style && typeof style === 'object') {
      return { ...base, ...style };
    }
    return base;
  }, [style]);

  const rootProps = {
    [UI_ATTRIBUTES.ROOT]: '',
    [UI_ATTRIBUTES.DISABLED_CATEGORIES]: disabledCategoriesAttr,
    [UI_ATTRIBUTES.HIDDEN_ITEMS]: hiddenItemsAttr,
  };

  return (
    <UIContainerContext.Provider value={containerContextValue}>
      <div ref={rootRefCallback} {...rootProps} {...restProps} style={combinedStyle}>
        {children}
      </div>
    </UIContainerContext.Provider>
  );
}
