// packages/plugin-a11y/src/shared/components/struct-element-component.tsx
import type { StructElement as StructElementModel } from '@embedpdf/plugin-a11y';
import { getFontClassName } from '../../lib/utils';
import { useEffect, useRef } from 'react';
import { computeStructElementViewModel } from './struct-element-viewmodel';

interface Props {
  element: StructElementModel;
  scale: number;
  parentLanguage?: string;
}

export function StructElementComponent({ element, scale, parentLanguage }: Props) {
  const elementRef = useRef<HTMLElement>(null);

  const viewModel = computeStructElementViewModel(element, scale, parentLanguage);
  const Tag = viewModel.tagName as any;

  useEffect(() => {
    if (elementRef.current != null && !elementRef.current.closest('.embedpdf-a11y-layer')) {
      console.error('StructElementComponent must be rendered within an A11yLayer component.');
    }
  });

  return (
    <Tag {...viewModel.attrs} style={viewModel.elementStyle} data-pdftag={element.tag} ref={elementRef}>
      {viewModel.textRuns.map((run, i) => (
        <span
          key={i}
          className={(() => {
            const fontClass = getFontClassName(
              run.fontFamily,
              run.fontSize,
              run.fontWeight,
              run.fontItalic,
            );
            return fontClass ? `${fontClass} textrun` : 'textrun';
          })()}
          style={run.style}
          role="presentation"
        >
          {run.text}
        </span>
      ))}
      {element.children.map((child, i) => (
        <StructElementComponent
          key={i}
          element={child}
          scale={scale}
          parentLanguage={viewModel.nextParentLanguage}
        />
      ))}
    </Tag>
  );
}

// packages/plugin-a11y/src/vue/components/struct-element-component.vue
<script setup lang="ts">
import { computed, onMounted, ref, toRefs } from 'vue';
import type { StructElement } from '@embedpdf/plugin-a11y';
import { getFontClassName } from '../../lib/utils';
import { computeStructElementViewModel } from '../../shared/components/struct-element-viewmodel';

defineOptions({ name: 'StructElementComponent' });

const props = defineProps<{
  element: StructElement;
  scale: number;
  parentLang?: string;
}>();
const { element, scale, parentLang } = toRefs(props);

const viewModel = computed(() =>
  computeStructElementViewModel(element.value, scale.value, parentLang.value),
);

const tagName = computed(() => viewModel.value.tagName as any);

const runs = computed(() =>
  viewModel.value.textRuns.map((run) => {
    const baseClass = getFontClassName(run.fontFamily, run.fontSize, run.fontWeight, run.fontItalic);
    return {
      ...run,
      className: baseClass ? `${baseClass} textrun` : 'textrun',
    };
  }),
);

const nextParentLang = computed(() => viewModel.value.nextParentLanguage);

const rootEl = ref<HTMLElement | null>(null);

onMounted(() => {
  if (rootEl.value && !rootEl.value.closest('.embedpdf-a11y-layer')) {
    console.error('StructElementComponent must be rendered within an A11yLayer component.');
  }
});
</script>

<template>
  <component
    :is="tagName"
    v-bind="viewModel.attrs"
    :style="viewModel.elementStyle"
    :data-pdftag="element.tag"
    ref="rootEl"
  >
    <span
      v-for="(run, i) in runs"
      :key="i"
      :class="run.className"
      :style="run.style"
    >
      {{ run.text }}
    </span>
    <StructElementComponent
      v-for="(child, index) in element.children"
      :key="index"
      :element="child"
      :scale="scale"
      :parent-lang="nextParentLang"
    />
  </component>
</template>
