// examples/react-mui/src/application.tsx
import { createPluginRegistration } from '@embedpdf/core';
import { EmbedPDF } from '@embedpdf/core/react';
import { usePdfiumEngine } from '@embedpdf/engines/react';
import { ConsoleLogger, PdfAnnotationSubtype, PdfStampAnnoObject } from '@embedpdf/models';
import { Viewport, ViewportPluginPackage } from '@embedpdf/plugin-viewport/react';
import { Scroller, ScrollPluginPackage, ScrollStrategy } from '@embedpdf/plugin-scroll/react';
import { LoaderPluginPackage } from '@embedpdf/plugin-loader/react';
import { RenderLayer, RenderPluginPackage } from '@embedpdf/plugin-render/react';
import { A11yLayer, A11yPluginPackage } from '@embedpdf/plugin-a11y/react';
import { TilingLayer, TilingPluginPackage } from '@embedpdf/plugin-tiling/react';
import { MarqueeZoom, ZoomMode, ZoomPluginPackage } from '@embedpdf/plugin-zoom/react';
import { SearchLayer, SearchPluginPackage } from '@embedpdf/plugin-search/react';
import {
  GlobalPointerProvider,
  PagePointerProvider,
  InteractionManagerPluginPackage,
} from '@embedpdf/plugin-interaction-manager/react';
import { PanPluginPackage } from '@embedpdf/plugin-pan/react';
import { Rotate, RotatePluginPackage } from '@embedpdf/plugin-rotate/react';
import { SpreadPluginPackage } from '@embedpdf/plugin-spread/react';
import { FullscreenPluginPackage } from '@embedpdf/plugin-fullscreen/react';
import { ExportPluginPackage } from '@embedpdf/plugin-export/react';
import { RedactionLayer, RedactionPluginPackage } from '@embedpdf/plugin-redaction/react';
import { ThumbnailPluginPackage } from '@embedpdf/plugin-thumbnail/react';
import { SelectionPluginPackage } from '@embedpdf/plugin-selection/react';
import { SelectionLayer } from '@embedpdf/plugin-selection/react';
import {
  AnnotationLayer,
  AnnotationPlugin,
  AnnotationPluginPackage,
  AnnotationTool,
} from '@embedpdf/plugin-annotation/react';

import { CircularProgress, Box, Alert } from '@mui/material';
import SearchOutlinedIcon from '@mui/icons-material/SearchOutlined';
import { useMemo, useRef } from 'react';

import { PageControls } from './components/page-controls';
import { Search } from './components/search';
import { Drawer, DrawerComponent, DrawerProvider } from './components/drawer-system';
import { Sidebar } from './components/sidebar';
import { Toolbar } from './components/toolbar';
import { ViewSidebarReverseIcon } from './icons';
import { AnnotationSelectionMenu } from './components/annotation-selection-menu';
import { RedactionSelectionMenu } from './components/redaction-selection-menu';

const plugins = [
  createPluginRegistration(LoaderPluginPackage, {
    loadingOptions: {
      type: 'url',
      pdfFile: {
        id: 'pdf',
        url: 'https://snippet.embedpdf.com/ebook.pdf',
      },
    },
  }),
  createPluginRegistration(ViewportPluginPackage, {
    viewportGap: 10,
  }),
  createPluginRegistration(ScrollPluginPackage, {
    strategy: ScrollStrategy.Vertical,
  }),
  createPluginRegistration(RenderPluginPackage),
  createPluginRegistration(TilingPluginPackage, {
    tileSize: 768,
    overlapPx: 2.5,
    extraRings: 0,
  }),
  createPluginRegistration(ZoomPluginPackage, {
    defaultZoomLevel: ZoomMode.FitPage,
  }),
  createPluginRegistration(SearchPluginPackage),
  createPluginRegistration(InteractionManagerPluginPackage),
  createPluginRegistration(PanPluginPackage),
  createPluginRegistration(RotatePluginPackage),
  createPluginRegistration(SpreadPluginPackage),
  createPluginRegistration(FullscreenPluginPackage),
  createPluginRegistration(ExportPluginPackage),
  createPluginRegistration(ThumbnailPluginPackage, {
    paddingY: 10,
  }),
  createPluginRegistration(SelectionPluginPackage),
  createPluginRegistration(A11yPluginPackage, { debug: true }), // overlay toggled via `debug`
  createPluginRegistration(AnnotationPluginPackage),
  createPluginRegistration(RedactionPluginPackage),
];

const drawerComponents: DrawerComponent[] = [
  {
    id: 'search',
    component: Search,
    icon: SearchOutlinedIcon,
    label: 'Search',
    position: 'right',
  },
  {
    id: 'sidebar',
    component: Sidebar,
    icon: ViewSidebarReverseIcon,
    label: 'Sidebar',
    position: 'left',
  },
];

const consoleLogger = new ConsoleLogger();

function App() {
  const isDev = useMemo(
    () => new URLSearchParams(window.location.search).get('dev') === 'true',
    [],
  );

  const { engine, isLoading, error } = usePdfiumEngine(isDev ? { logger: consoleLogger } : {});
  const popperContainerRef = useRef<HTMLDivElement>(null);

  if (error) {
    return (
      <Box
        sx={{
          height: '100%',
          width: '100%',
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
        <Alert severity="error">Failed to initialize PDF viewer:</Alert>
      </Box>
    );
  }

  if (isLoading || !engine) {
    return (
      <Box
        sx={{
          height: '100%',
          width: '100%',
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
        <CircularProgress size={48} />
      </Box>
    );
  }

  return (
    <DrawerProvider components={drawerComponents}>
      <EmbedPDF
        engine={engine}
        plugins={plugins}
        onInitialized={async (registry) => {
          const annotation = registry.getPlugin<AnnotationPlugin>('annotation')?.provides();
          annotation?.addTool<AnnotationTool<PdfStampAnnoObject>>({
            id: 'stampApproved',
            name: 'Stamp Approved',
            interaction: {
              exclusive: false,
              cursor: 'crosshair',
            },
            matchScore: () => 0,
            defaults: {
              type: PdfAnnotationSubtype.STAMP,
              imageSrc:
                'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Eo_circle_green_checkmark.svg/512px-Eo_circle_green_checkmark.svg.png',
              imageSize: { width: 20, height: 20 },
            },
          });
        }}
      >
        {({ pluginsReady }) => (
          <Box
            sx={{
              height: '100%',
              width: '100%',
              display: 'flex',
              flexDirection: 'column',
              position: 'relative',
              userSelect: 'none',
            }}
          >
            <Toolbar />

            {/* Main content area with sidebars */}
            <Box sx={{ display: 'flex', flexGrow: 1, overflow: 'hidden' }}>
              {/* Left Sidebar */}
              <Drawer position="left" />

              {/* Main Viewport */}
              <Box
                ref={popperContainerRef}
                sx={{
                  flex: '1 1 0', // grow / shrink, flex-basis 0
                  minWidth: 0, // allow shrinking inside flex row
                  display: 'flex',
                  flexDirection: 'column',
                  position: 'relative',
                }}
              >
                <GlobalPointerProvider>
                  <Viewport
                    style={{
                      width: '100%',
                      height: '100%',
                      flexGrow: 1,
                      backgroundColor: '#f1f3f5',
                      overflow: 'auto',
                    }}
                  >
                    {!pluginsReady && (
                      <Box
                        sx={{
                          display: 'flex',
                          justifyContent: 'center',
                          alignItems: 'center',
                          height: '100%',
                          width: '100%',
                        }}
                      >
                        <CircularProgress size={48} />
                      </Box>
                    )}
                    {pluginsReady && (
                      <Scroller
                        renderPage={({ document, width, height, pageIndex, scale, rotation }) => (
                          <Rotate key={document?.id} pageSize={{ width, height }}>
                            <PagePointerProvider
                              pageIndex={pageIndex}
                              pageWidth={width}
                              pageHeight={height}
                              rotation={rotation}
                              scale={scale}
                            >
                              <RenderLayer
                                pageIndex={pageIndex}
                                style={{ pointerEvents: 'none' }}
                                aria-hidden='true'
                              />
                              <A11yLayer pageIndex={pageIndex} scale={scale} />
                              <TilingLayer
                                pageIndex={pageIndex}
                                scale={scale}
                                style={{ pointerEvents: 'none' }}
                                aria-hidden='true'
                              />
                              <SearchLayer
                                pageIndex={pageIndex}
                                scale={scale}
                                style={{ pointerEvents: 'none' }}
                                aria-hidden='true'
                              />
                              <MarqueeZoom pageIndex={pageIndex} scale={scale} />
                              <SelectionLayer pageIndex={pageIndex} scale={scale} />
                              <RedactionLayer
                                pageIndex={pageIndex}
                                scale={scale}
                                rotation={rotation}
                                selectionMenu={({ menuWrapperProps, selected, item }) => (
                                  <>
                                    {selected ? (
                                      <RedactionSelectionMenu
                                        menuWrapperProps={menuWrapperProps}
                                        selected={item}
                                        container={popperContainerRef.current}
                                      />
                                    ) : null}
                                  </>
                                )}
                              />
                              <AnnotationLayer
                                pageIndex={pageIndex}
                                scale={scale}
                                pageWidth={width}
                                pageHeight={height}
                                rotation={rotation}
                                selectionMenu={({ menuWrapperProps, selected, annotation }) => (
                                  <>
                                    {selected ? (
                                      <AnnotationSelectionMenu
                                        menuWrapperProps={menuWrapperProps}
                                        selected={annotation}
                                        container={popperContainerRef.current}
                                      />
                                    ) : null}
                                  </>
                                )}
                              />
                            </PagePointerProvider>
                          </Rotate>
                        )}
                      />
                    )}
                    <PageControls />
                  </Viewport>
                </GlobalPointerProvider>
              </Box>

              {/* Right Sidebar */}
              <Drawer position="right" />
            </Box>
          </Box>
        )}
      </EmbedPDF>
    </DrawerProvider>
  );
}

export default App;

// examples/vue-vuetify/src/components/Application.vue
<script setup lang="ts">
import { usePdfiumEngine } from '@embedpdf/engines/vue';
import { EmbedPDF } from '@embedpdf/core/vue';
import { createPluginRegistration, PluginRegistry } from '@embedpdf/core';
import { LoaderPluginPackage } from '@embedpdf/plugin-loader/vue';
import { Viewport, ViewportPluginPackage } from '@embedpdf/plugin-viewport/vue';
import { Scroller, ScrollPluginPackage, ScrollStrategy } from '@embedpdf/plugin-scroll/vue';
import { RenderLayer, RenderPluginPackage } from '@embedpdf/plugin-render/vue';
import { A11yLayer, A11yPluginPackage } from '@embedpdf/plugin-a11y/vue';
import { TilingLayer, TilingPluginPackage } from '@embedpdf/plugin-tiling/vue';
import { SelectionLayer, SelectionPluginPackage } from '@embedpdf/plugin-selection/vue';
import {
  InteractionManagerPluginPackage,
  GlobalPointerProvider,
  PagePointerProvider,
} from '@embedpdf/plugin-interaction-manager/vue';
import { RotatePluginPackage } from '@embedpdf/plugin-rotate/vue';
import { Rotate } from '@embedpdf/plugin-rotate/vue';
import { FullscreenPluginPackage } from '@embedpdf/plugin-fullscreen/vue';
import { ZoomMode, ZoomPluginPackage, MarqueeZoom } from '@embedpdf/plugin-zoom/vue';
import { PanPluginPackage } from '@embedpdf/plugin-pan/vue';
import { ExportPluginPackage } from '@embedpdf/plugin-export/vue';
import { SpreadPluginPackage } from '@embedpdf/plugin-spread/vue';
import { PrintPluginPackage } from '@embedpdf/plugin-print/vue';
import { SearchPluginPackage, SearchLayer } from '@embedpdf/plugin-search/vue';
import { ThumbnailPluginPackage } from '@embedpdf/plugin-thumbnail/vue';
import { RedactionPluginPackage, RedactionLayer } from '@embedpdf/plugin-redaction/vue';
import {
  AnnotationPluginPackage,
  AnnotationLayer,
  AnnotationPlugin,
} from '@embedpdf/plugin-annotation/vue';
import type { AnnotationTool } from '@embedpdf/plugin-annotation/vue';
import { PdfAnnotationSubtype } from '@embedpdf/models';
import type { PdfStampAnnoObject } from '@embedpdf/models';

import Toolbar from './Toolbar.vue';
import DrawerProvider from './drawer-system/DrawerProvider.vue';
import Drawer from './drawer-system/Drawer.vue';
import Search from './Search.vue';
import Sidebar from './Sidebar.vue';
import RedactionSelectionMenu from './RedactionSelectionMenu.vue';
import AnnotationSelectionMenu from './AnnotationSelectionMenu.vue';
import { AllLogger, ConsoleLogger } from '@embedpdf/models';
// Define drawer components
const drawerComponents = [
  {
    id: 'search',
    component: Search,
    icon: 'mdi-magnify',
    label: 'Search',
    position: 'right' as const,
  },
  {
    id: 'sidebar',
    component: Sidebar,
    icon: 'mdi-dock-left',
    label: 'Sidebar',
    position: 'left' as const,
  },
];

const { engine, isLoading: engineLoading, error: engineError } = usePdfiumEngine();

const handleInitialized = async (registry: PluginRegistry) => {
  const annotation = registry.getPlugin<AnnotationPlugin>('annotation')?.provides();
  annotation?.addTool<AnnotationTool<PdfStampAnnoObject>>({
    id: 'stampApproved',
    name: 'Stamp Approved',
    interaction: {
      exclusive: false,
      cursor: 'crosshair',
    },
    matchScore: () => 0,
    defaults: {
      type: PdfAnnotationSubtype.STAMP,
      imageSrc:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Eo_circle_green_checkmark.svg/512px-Eo_circle_green_checkmark.svg.png',
      imageSize: { width: 20, height: 20 },
    },
  });
};
</script>

<template>
  <!-- Loading state -->
  <div v-if="engineLoading" class="d-flex fill-height align-center justify-center">
    <div class="text-center">
      <v-progress-circular indeterminate color="primary" size="64"></v-progress-circular>
      <div class="text-body-1 text-medium-emphasis mt-4">Loading PDF engine...</div>
    </div>
  </div>

  <!-- Error state -->
  <div v-else-if="engineError" class="d-flex fill-height align-center justify-center">
    <v-alert type="error" variant="tonal" class="ma-4">
      <v-alert-title>Error</v-alert-title>
      {{ engineError.message }}
    </v-alert>
  </div>

  <!-- Main application -->
  <div v-else-if="engine" class="fill-height">
    <EmbedPDF
      :engine="engine"
      :on-initialized="handleInitialized"
      :plugins="[
        createPluginRegistration(LoaderPluginPackage, {
          loadingOptions: {
            type: 'url',
            pdfFile: {
              id: 'sample-pdf',
              name: 'embedpdf-ebook.pdf',
              url: 'https://snippet.embedpdf.com/ebook.pdf',
            },
          },
        }),
        createPluginRegistration(ViewportPluginPackage, {
          viewportGap: 10,
        }),
        createPluginRegistration(ScrollPluginPackage, {
          strategy: ScrollStrategy.Vertical,
          pageGap: 10,
        }),
        createPluginRegistration(RenderPluginPackage),
        createPluginRegistration(A11yPluginPackage),
        createPluginRegistration(TilingPluginPackage, {
          tileSize: 768,
          overlapPx: 2.5,
          extraRings: 0,
        }),
        createPluginRegistration(InteractionManagerPluginPackage),
        createPluginRegistration(SelectionPluginPackage),
        createPluginRegistration(RotatePluginPackage),
        createPluginRegistration(FullscreenPluginPackage),
        createPluginRegistration(ZoomPluginPackage, {
          defaultZoomLevel: ZoomMode.FitPage,
        }),
        createPluginRegistration(PanPluginPackage),
        createPluginRegistration(ExportPluginPackage),
        createPluginRegistration(SpreadPluginPackage),
        createPluginRegistration(PrintPluginPackage),
        createPluginRegistration(ThumbnailPluginPackage, {
          imagePadding: 10,
          labelHeight: 25,
        }),
        createPluginRegistration(SearchPluginPackage, {
          flags: [],
          showAllResults: true,
        }),
        createPluginRegistration(RedactionPluginPackage),
        createPluginRegistration(AnnotationPluginPackage),
      ]"
    >
      <template #default="{ pluginsReady }">
        <DrawerProvider :components="drawerComponents">
          <v-layout class="fill-height" id="pdf-app-layout">
            <!-- Toolbar -->
            <Toolbar />

            <!-- Left Drawer -->
            <Drawer position="left" />

            <!-- Main content -->
            <v-main class="fill-height">
              <div class="fill-height position-relative">
                <GlobalPointerProvider>
                  <Viewport class="fill-height" style="background-color: #f5f5f5; overflow: auto">
                    <div
                      v-if="!pluginsReady"
                      class="d-flex fill-height align-center justify-center"
                    >
                      <div class="text-center">
                        <v-progress-circular
                          indeterminate
                          color="primary"
                          size="48"
                        ></v-progress-circular>
                        <div class="text-body-1 text-medium-emphasis mt-4">Loading plugins...</div>
                      </div>
                    </div>
                    <Scroller v-else>
                      <template #default="{ page }">
                        <Rotate
                          :key="page.document?.id"
                          :page-size="{ width: page.width, height: page.height }"
                        >
                          <PagePointerProvider
                            :page-index="page.pageIndex"
                            :page-width="page.width"
                            :page-height="page.height"
                            :rotation="page.rotation"
                            :scale="page.scale"
                            class="position-absolute"
                          >
                            <RenderLayer
                              :page-index="page.pageIndex"
                              style="pointer-events: none"
                            />
                            <TilingLayer
                              :page-index="page.pageIndex"
                              :scale="page.scale"
                              style="pointer-events: none"
                            />
                            <A11yLayer :page-index="page.pageIndex" :scale="page.scale"></A11yLayer>
                            <MarqueeZoom :page-index="page.pageIndex" :scale="page.scale" />
                            <SearchLayer :page-index="page.pageIndex" :scale="page.scale" />
                            <AnnotationLayer
                              :page-index="page.pageIndex"
                              :scale="page.scale"
                              :page-width="page.width"
                              :page-height="page.height"
                              :rotation="page.rotation"
                            >
                              <template
                                #selection-menu="{ annotation, selected, menuWrapperProps, rect }"
                              >
                                <AnnotationSelectionMenu
                                  v-if="selected"
                                  :annotation="annotation"
                                  :menu-wrapper-props="menuWrapperProps"
                                  :rect="rect"
                                />
                              </template>
                            </AnnotationLayer>
                            <RedactionLayer
                              :page-index="page.pageIndex"
                              :scale="page.scale"
                              :rotation="page.rotation"
                            >
                              <template
                                #selection-menu="{ item, selected, menuWrapperProps, rect }"
                              >
                                <RedactionSelectionMenu
                                  v-if="selected"
                                  :item="item"
                                  :menu-wrapper-props="menuWrapperProps"
                                  :rect="rect"
                                />
                              </template>
                            </RedactionLayer>
                            <SelectionLayer :page-index="page.pageIndex" :scale="page.scale" />
                          </PagePointerProvider>
                        </Rotate>
                      </template>
                    </Scroller>
                    <!-- Page Controls Overlay -->
                    <PageControls />
                  </Viewport>
                </GlobalPointerProvider>
              </div>
            </v-main>

            <!-- Right Drawer -->
            <Drawer position="right" />
          </v-layout>
        </DrawerProvider>
      </template>
    </EmbedPDF>
  </div>

  <!-- Engine not ready state -->
  <div v-else class="d-flex fill-height align-center justify-center">
    <div class="text-body-1 text-medium-emphasis text-center">Engine not ready</div>
  </div>
</template>

<style scoped>
#pdf-app-layout {
  user-select: none;
}
.flex-1-1-100 {
  flex: 1 1 100%;
}
</style>
